### ISSUE TITLE
etcd storageclass not able to provision gp3 disk

### ISSUE THREAD

**Issue by mindthevirt** [pachyderm/helmchart#93]
In order to provision a gp3 disk for etcd on eks, we need to use the [aws ebs csi driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) as the provisioner.

The following change has to be made in the storageclass:

```
# Source: pachyderm/templates/etcd/storageclass.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd-storage-class
parameters:
  type: gp3
provisioner: ebs.csi.aws.com >>>> I changed this to make it work.
```
